<?php
/**
 * @file
 * Contains sharerich.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function sharerich_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'sharerich.admin_settings_form':
      $output = '';
      $output .= '<p>' . t('You can manage your Sharerich sets at <a href=":menu-settings">Structure > Sharerich</a>.', array(':menu-settings' => \Drupal::url('entity.sharerich.collection'))) . '</p>';
      return $output;
    break;

    case 'entity.sharerich.collection':
      $output = '';
      $output .= '<p>' . t('Global settings are available at the <a href=":menu-settings">configuration page</a>.', array(':menu-settings' => \Drupal::url('sharerich.admin_settings_form'))) . '</p>';
      return $output;
    break;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function sharerich_theme() {
  $theme = [];

  return $theme;
}

/**
 * Helper to scan the services folder.
 * @return A list of file names.
 */
function sharerich_get_default_services() {
  $dir = drupal_get_path('module', 'sharerich') . '/services';
  $list = file_scan_directory($dir, '/.inc/', array(), 0);
  return array_map(function($service) {
    return $service->name;
  }, $list);
}

/**
 * Helper to load services from the disk.
 */
function sharerich_load_default_service($service_name) {
  $dir = drupal_get_path('module', 'sharerich') . '/services';
  $service_name = $dir . '/' . $service_name . '.inc';
  if (file_exists($service_name)) {
    return file_get_contents($service_name);
  }
  return FALSE;
}
