<?php
/**
 * @file
 * Module file for Sharerich.
 */

/**
 * Implements hook_menu().
 */
function sharerich_menu() {
  $items['admin/config/user-interface/sharerich'] = array(
    'title' => 'Sharerich',
    'description' => t('Configure the Sharerich to select which social buttons you would like to enable.'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('sharerich_admin_form'),
    'access callback' => 'user_access',
    'access arguments' => array('administer sharerich'),
    'file' => 'sharerich.admin.inc',
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

/**
 * Implements hook_permission().
 */
function sharerich_permission() {
  return array(
    'administer sharerich' => array(
      'title' => t('Administer Sharerich'),
      'description' => t('Permission to allow user to configure Sharerich.'),
      'restrict access' => TRUE,
    ),
  );
}


/**
 * Implements hook_block_info().
 */
function sharerich_block_info() {
  $blocks['sharerich'] = array(
    'info' => t('Sharerich'),
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function sharerich_block_view($delta = '') {
  $block = array();
  switch ($delta) {
    case 'sharerich':
      $block['subject'] = t('Share this');
      $block['content'] = array(
        '#markup' => sharerich_get_buttons(),
      );
  }
  return $block;
}

/**
 * Returns markup with list of share buttons.
 */
function sharerich_get_buttons() {
  foreach (variable_get('sharerich_services', array()) as $service_name) {
    if (!empty(variable_set('sharerich_custom_' . $service_name, ''))) {
      $content = variable_set('sharerich_custom_' . $service_name);
    }
    else {
      $content = sharerich_load_service($service_name);
    }
    // Tokens replacement.
    $buttons[$service_name] = token_replace($content, array($node));
  }

  $items = array();
  $defaults = array('email', 'facebook', 'linkedin', 'twitter', 'googleplus', 'pinterest');
  $services = variable_get('sharerich_services', $defaults);
  foreach ($services as $key => $value) {
    if ($value) {
      // Allow other modules to alter the buttons markup.
      drupal_alter('sharerich_buttons', $buttons);

      $items[] = array(
        'data' => $buttons[$value],
        'class' => array($key),
      );
    }
    else {
      continue;
    }
  }

  $attributes = array(
    'class' => array('sharerich-buttons', 'clearfix'),
  );
  return theme_item_list(array('items' => $items, 'title' => '', 'type' => 'ul', 'attributes' => $attributes));
}
