<a href="https://news.ycombinator.com/submitlink?u=http://www.kurtnoble.com/labs/rrssb/&amp;t=Check%20out%20how%20ridiculously%20responsive%20these%20social%20buttons%20are&amp;text=Check%20out%20how%20ridiculously%20responsive%20these%20social%20buttons%20are">
  <span class="rrssb-icon">
    <svg xmlns="http://www.w3.org/2000/svg" width="28" height="28" viewbox="0 0 28 28">
      <path fill="#FFF" d="M14 13.626l-4.508-9.19H6.588l6.165 12.208v6.92h2.51v-6.92l6.15-12.21H18.69"></path>
    </svg>
  </span>
  <span class="rrssb-text">hackernews</span>
</a>